import React, { useEffect, useState } from "react";
import { Alert, Button, Card, Empty, Spin, Statistic } from "antd";
import { CalendarOutlined, ClockCircleOutlined, DollarOutlined, PlusOutlined, ScheduleOutlined, WalletOutlined } from "@ant-design/icons";
import { Area, AreaChart, CartesianGrid, ResponsiveContainer, Tooltip, XAxis, YAxis } from "recharts";
import axios from "axios";
import { useNavigate } from "react-router-dom";
import { API_URL } from "../utils/ApiUrl";
import "./ProviderDashboard.css";

const money = (value) => `₹${Number(value || 0).toLocaleString("en-IN")}`;
const providerWords = { "Venue Admin": { noun: "venue", plural: "venues", list: "/venues", add: "/venues/add", availability: "Manage slots" }, Coach: { noun: "coach", plural: "coaches", list: "/coaches", add: "/coach/add", availability: "Manage availability" }, "Personal Trainer": { noun: "trainer", plural: "trainers", list: "/personal-training", add: "/personal-training/add", availability: "Manage availability" } };

export default function ProviderDashboard({ role }) {
  const navigate = useNavigate(); const words = providerWords[role];
  const [loading, setLoading] = useState(true); const [error, setError] = useState(""); const [summary, setSummary] = useState({}); const [monthly, setMonthly] = useState([]); const [recent, setRecent] = useState([]);
  const refresh = async () => { try { setLoading(true); setError(""); const headers = { Authorization: `Bearer ${localStorage.getItem("token")}` }; const [s, m, r] = await Promise.all([axios.get(`${API_URL}/earnings/summary`, { headers }), axios.get(`${API_URL}/earnings/monthly`, { headers }), axios.get(`${API_URL}/earnings/recent-bookings`, { headers })]); setSummary(s.data.data || {}); setMonthly(m.data.data || []); setRecent(r.data.data || []); } catch (e) { setError(e.response?.data?.message || "Could not load your dashboard."); } finally { setLoading(false); } };
  useEffect(() => { refresh(); }, []);
  if (loading) return <div className="provider-loading"><Spin size="large" /><span>Loading your workspace…</span></div>;
  const cards = [["Net earnings", summary.totalEarnings, <WalletOutlined />, true], ["This month", summary.thisMonthEarnings, <DollarOutlined />, true], ["Bookings", summary.totalBookings, <CalendarOutlined />], ["Refunded", summary.totalRefunded, <ScheduleOutlined />, true]];
  return <div className="provider-dashboard"><section className="provider-hero"><div><p>{role.toUpperCase()} WORKSPACE</p><h1>Your day, at a glance.</h1><span>Review bookings, availability, and earnings for your {words.plural}.</span></div><Button icon={<ClockCircleOutlined />} onClick={refresh}>Refresh</Button></section>{error && <Alert type="error" message={error} showIcon className="mb-3" />}<div className="provider-kpis">{cards.map(([label, value, icon, isMoney]) => <Card key={label} bordered={false}><Statistic title={label} value={isMoney ? money(value) : value || 0} prefix={icon} /></Card>)}</div><div className="provider-actions"><div><p>QUICK ACTIONS</p><h2>Manage your business</h2></div><div><Button type="primary" icon={<PlusOutlined />} onClick={() => navigate(words.add)}>Add {words.noun}</Button><Button icon={<CalendarOutlined />} onClick={() => navigate(words.list)}>{words.availability}</Button><Button icon={<WalletOutlined />} onClick={() => navigate("/earnings")}>View earnings</Button></div></div><div className="provider-grid"><Card title="Earnings trend" bordered={false}>{monthly.length ? <ResponsiveContainer width="100%" height={260}><AreaChart data={monthly}><defs><linearGradient id="providerIncome" x1="0" y1="0" x2="0" y2="1"><stop offset="0" stopColor="#0b8a5a" stopOpacity=".3" /><stop offset="1" stopColor="#0b8a5a" stopOpacity="0" /></linearGradient></defs><CartesianGrid vertical={false} strokeDasharray="3 3" /><XAxis dataKey="month" /><YAxis /><Tooltip formatter={(v) => money(v)} /><Area dataKey="earnings" stroke="#0b8a5a" fill="url(#providerIncome)" strokeWidth={3} /></AreaChart></ResponsiveContainer> : <Empty description="No earnings data yet" />}</Card><Card title="Recent bookings" bordered={false}>{recent.length ? <div className="provider-recent">{recent.slice(0, 5).map((item) => <div key={item.id}><div><strong>{item.service}</strong><span>{item.user || "Customer"}</span></div><b>{money(item.netAmount)}</b></div>)}</div> : <Empty description="No bookings yet" />}</Card></div></div>;
}
